// import type { Metadata } from "next";

// import "./globals.css";
// import { ToastContainer } from "react-toastify";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={` antialiased`}>
//         <ToastContainer />
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";

export const metadata = {
  title: "Your App",
  description: "Next.js app with Redux setup",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
